name: Deploy Static Content to GitHub Pages

on:
  workflow_run:
    workflows: ["Lint Static Content"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Website
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
      #name: github-pages
      #url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Step 1 - Display Deployment Information
        run: |
          echo "========================================"
          echo "GitHub Pages Deployment Started"
          echo "Repository : ${{ github.repository }}"
          echo "Workflow   : ${{ github.workflow }}"
          echo "Triggered By Previous Workflow"
          echo "========================================"

      - name: Step 2 - Checkout Repository
        uses: actions/checkout@v4

      - name: Step 3 - Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Step 4 - Upload Website Files
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."

      - name: Step 5 - Deploy Website to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Step 6 - Display Deployment URL
        run: |
          echo "========================================"
          echo "Deployment Completed Successfully!"
          echo "Website URL:"
          echo "${{ steps.deployment.outputs.page_url }}"
          echo "========================================"