name: Lint Static Content

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  # 🔍 Check for HTML and CSS errors
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check HTML Errors
        uses: htmlhint/htmlhint-action@v2
        with:
          file_pattern: '**/*.html'

      - name: Check CSS Errors
        uses: reviewdog/action-stylelint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          stylelint_input: '**/*.css'
